### ISSUE TITLE
Packagist "dev-develop" refference is not updated.

### ISSUE THREAD

**Issue by koriym** [auraphp/Aura.Input#20]
Current packagist 'dev-develop' points old reference.
https://packagist.org/packages/aura/input

```
reference: 5c949cf ( 2013-05-09 21:22 UTC)
```

Its not latest.
https://github.com/auraphp/Aura.Input/commits/develop

Web hook failed ?

**Comment by pmjones** [comment]
No, @pmjones failed. The release script does not error when the "keywords" metafile is empty, and so an empty set of keywords got put into composer.json.  I have remedied this by hand in the develop branch of Aura.Input to add keywords, but master will still be wrong until we do a new release (and until I fix the release script, which will be next).  Thanks for pointing out the problem.
