### ISSUE TITLE
Fieldsets and collections

### ISSUE THREAD

**Issue by dmolineus** [auraphp/Aura.Input#33]
I'm evaluating aura for using it as a form component. It looks very promising. Thanks for your work!

I am struggling with fieldsets at the moment. I would like to use them to group my input fields into them and render a html fieldset. Setting it up is all fine, rendering as well. But I struggle with filling the field data.
- If I render the fieldset as fieldset, the name of the fieldset wont be set as input var, so the fields of the fieldset does not get filled
- If I render a hidden field for the fieldset, Aura.Input tries to fill the children as well. But it does not pass the data array, only the given string.

Did I miss something? Is there another way? Or what is the purpose of the fieldsets/collections?

**Comment by dmolineus** [comment]
Okay, I I got it. Because I use subtemplates I used `Field::get()` instead of `Fieldset::get('field')`. The first one does not use the full name, so the children could not get the form data. Is it a good idea that both methods differ?

**Comment by harikt** [comment]
I am confused. Do you have some code ?

**Comment by dmolineus** [comment]
Yes, of course. It's a simple setup. The default fieldset returns an empty one.

``` php
$fieldset = $f->setFieldset('fieldset', 'default');
$field = $fieldset->setField('input');

var_export($field->get());
var_export($fieldset->get('input'));
```

If I call `$fieldset->get('input')` first, then both returns the full name. The issue seems that the name prefix is not set when `setField` is called.

**Comment by harikt** [comment]
Did you had a look at https://github.com/auraphp/Aura.Input/blob/develop/tests/Aura/Input/Example/ExampleTest.php 

I want to look into it deeply, didn't get. Will look into it in the morning.

**Comment by harikt** [comment]
@netzmacht got anything or are you still struggling ?

**Comment by dmolineus** [comment]
@harikt I have taken a look to the tests. I can work around the issue but I think its a bug of Aura.Input. Your tests don't cover this. Please take a look at my example above and examine the name returned of `$field->get()`

**Comment by harikt** [comment]
@netzmacht one of the problem I am facing is your code is not runnable. What is `$f` ?

If you can write the full code I can run easily. 

Thanks

**Comment by dmolineus** [comment]
Sure, I created a gist for you. The only thing you have to change is to set up the autoloader for your environment.

There is an example Widget class inside to explain why I want to access the field directly.

https://gist.github.com/netzmacht/770d6ae06fd2597c3eb7

**Comment by harikt** [comment]
so, I tried the one you provided in gist.
It seems like a bug to me.

Reason is when you call `$form->get('some-name')` ( https://gist.github.com/netzmacht/770d6ae06fd2597c3eb7#file-test-php-L29 )  it appends the name prefix. ( https://github.com/auraphp/Aura.Input/blob/develop/src/Aura/Input/Fieldset.php#L316 ) . So the `contact` is set as the name prefix to the field.

And so the later call `$field->get()` https://gist.github.com/netzmacht/770d6ae06fd2597c3eb7#file-test-php-L38
will have the name prefix.

One thing you can do is call the 

``` php
$field1 = $form->getInput('email');
var_dump($field1->get()['name']);
```

rather than using the $field object returned. 

It can be fixed by setting the prefix on the `setField` https://github.com/auraphp/Aura.Input/blob/develop/src/Aura/Input/Fieldset.php#L255 

I would like to ping @pmjones , @koriym for further thoughts on this.

**Comment by harikt** [comment]
Though this seems a simple issue, my head seems whirling ;-) .
Thank you for reporting this.

**Comment by dabba39** [comment]
> ``` php
> $fieldset = $f->setFieldset('fieldset', 'default');
> $field = $fieldset->setField('input');
> 
> var_export($field->get());
> var_export($fieldset->get('input'));
> ```

the name prefix, like in <code>prefix['child_0']['child_1']</code> is used for rendering the form. So as your field is part of a fieldset, you would first render the fieldset and then the field.

Setting the name prefix is  a rendering  thing and should anyway not be part of a fieldset defining class.

**Comment by pmjones** [comment]
I think @dabba39 and @harikt have answered this. Let me know if there's still a problem.
