### ISSUE TITLE
Add an empty row to the collection 

### ISSUE THREAD

**Issue by dmolineus** [auraphp/Aura.Input#34]
I really like the idea of collections and fieldsets in Aura, but I struggle at some points. Here is another one.

At the moment an collection can only be rendered if any data is filled in (by a model, by post etc.). It would be great add an empty fieldset row or at least to get the fieldset so I could create empty rows in the View of the collection.

``` php
public function addEmptyFieldset()
{
    $index = $this->count();
    $new = $this->newFieldset($index);
    $this->fieldsets[$index] = $new;

    return $new;
}
```

**Comment by harikt** [comment]
What is the purpose of empty field set you are looking for ?

**Comment by dmolineus** [comment]
Let me explain it with the used contact form example in the Aura docs. I want to provide a form where multiple entries of the collection can be added. The number of items should not be limited. 

I would like to render an empty fieldset in this cases:
1. User registers: There is no data filled yet, so the collection would contain no fieldset rows. I want to display an empty row so the first item can be inserted
2. User edit data: User wants to add a new contact type. There need to be a new row.

I want to use a generic form renderer where I can not know which fieldset is used in the collection. So I need a way getting the fieldset.

**Comment by harikt** [comment]
ping @pmjones

**Comment by harikt** [comment]
could you please send a PR, so @pmjones can check the idea? ( preferable with test case ) or you can wait to hear his thoughts.

**Comment by harikt** [comment]
one thing for now, extend the class ;) .

**Comment by dabba39** [comment]
the collection class should not contain rendering concerns. empty fieldsets can be triggered via javascript.
