### ISSUE TITLE
May be a isSuccess flag

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Input#38]
Hi Paul, 

I was working on form, and submissions lately with the ADR .

The form is injected to the Domain\Contact . Now when the request method is post the form is calling `fill()` and  `filter()` .

We are setting the form back to the responder. 

One thing probably you may mention will be keep the get and post Actions different. But to me it seems duplicating so much efforts.

I was thinking whether it is good to have a `isSuccess()` method and return true / false if a check on `filter()` is called. Else nothing is returned.

Another thing is `getMessages()` can be checked for errors, but if the form is not submitted the `getMessages()` empty and that doesn't means it is success and display the message, the way `isSuccess` help us is recognize whether a call to filter has happened rather the user testing again on responder with certain flags set when a request is submitted etc.

Interested to hear your thoughts.

Thank you

**Comment by stephen-hill** [comment]
I like this suggestion and I'm willing to work on this if you both don't have the time.

I think that `isSuccess()` should throw an exception when `filter()` has not been called.

I would also like to suggest that `fill()` return `$this` so that it can be chained with filter:

``` php
$form->fill($data)->filter();

if ($form->isSuccess() === true) {
```

Cheers
Stephen

**Comment by pmjones** [comment]
I'm OK with fill() being fluent.

I'm also OK with an isSuccess(), though I'd like for it to be ternary (true/false, and null if filter has not been called).

I don't recall -- do we have an isFailure() method?

**Comment by stephen-hill** [comment]
I'm wondering why `isSuccess()` should return `null` if `filter()` hasn't been called? I feel like `isSuccess()` should not be called unless `filter()` has been called, and thus, should throw an exception.

``` php
$form->fill($data);
if ($form->isSuccess()) { // Throw exception
```

By throwing an exception, your telling the developer that they have missed something. Otherwise the developer could write code for an unknown state.

``` php
if ($form->isSuccess()) {
    // Save Data
} else {
    // Are we false or null? Should I check?
}
```

Would love to hear your thoughts.

There is no `isFailure()` method().

**Comment by harikt** [comment]
@stephen-hill I don't think I will be able to look into this for the current time.

Feel free to pickup and move forward.

Thank you.

**Comment by pmjones** [comment]
@stephen-hill seems to have finished this off.

**Comment by stephen-hill** [comment]
@pmjones Thanks for merging this addition.
