### ISSUE TITLE
Regarding "Add an addRule"

### ISSUE THREAD

**Issue by stephen-hill** [auraphp/Aura.Input#48]
Regarding #13, I'm wondering if we could discuss this again?

I feel add an additional `addRule` method would be really useful and would avoid developers having to write their own class that extends `Filter` or implements `FilterInterface`.

I don't think that having two method, `setRule` and `addRule`, would be confusing for developers.

Also, `Filter` currently supports multiple messages per `Field`, so I don't think there will be any BC breaking with the messages.

What are your current thoughts?

Cheers
Stephen

**Comment by stephen-hill** [comment]
Alternatively, #40 is a good compromise because it allows develops to write complicated rules within the closure.

**Comment by stephen-hill** [comment]
Another idea to add to the discussion is to allow the addition of some sort of `AdvancedFilter` class which can be allowed to have a range of methods such as:
- addRule($field, $message, $closure)
- setRequired($field, $message)
- mustBeEmail($field, $message)
- etc.

**Comment by stephen-hill** [comment]
So for the time being, I've written my own class which extends `Filter` and implements an `addRule()` method and a re-written `values()` method which handles multiple rules per field.

Would you seriously consider the addition of this additional class if I created a pull-request?

This will solve the problem of #39, and I could also merge in #40 too. So the original `Filter` class is left untouched but gives developers the option of using this new class which provides some extra functionality.

I'm using this library in a large application and would prefer to give back to the community, rather than keeping my own branch/fork. So I'm very happy to put in the work for some kind of solution or compromise. 

Many Thanks
Stephen

**Comment by pmjones** [comment]
> Would you seriously consider the addition of this additional class if I created a pull-request?

Sure, let's see the PR.

And thanks for doing the work!

**Comment by pmjones** [comment]
I think this is taken care of now that #40 is merged. Let me know if there's still trouble.

**Comment by stephen-hill** [comment]
Thanks Paul. #40 definitely achieves the same end result :)
