### ISSUE TITLE
Starting 3.x

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Input#51]
Hi all,

I am currently cleaning up the Aura.Input 1.x branch in order to move it to 3.x.

Are there any feature request / problems we need to resolve ?

Please create issues or discuss here.

Thank you

**Comment by jakejohns** [comment]
Is the plan here to figure out how to integrate `Filter` and `Input` via a 3rd `FilterInterface` package?

**Comment by harikt** [comment]
Hi @jakejohns ,

I have some plans for intergration of Aura.Input and Aura.Filter with a common Interface.

See https://github.com/auraphp/Aura.Input/blob/712aaa48785a9ab3e34f5e70199b53a8596a76e7/composer.json#L27

The basic idea is if Aura.Filter is going to release 3.x we could make use of https://github.com/harikt/Aura.Filter_Interface/blob/7104e5554d04c8111c13914ed805c13c2218e0d0/src/FilterInterface.php and https://github.com/harikt/Aura.Filter_Interface/blob/7104e5554d04c8111c13914ed805c13c2218e0d0/src/FailureCollectionInterface.php , so there is no need of a 3rd package to integrate Aura.Input and Aura.Filter . 

I have made the necessary changes and believe is good for review.

Let me know if that helps.

**Comment by harikt** [comment]
@pmjones Do you have any thoughts for the Filter_Interface ?

UPDATE : 

If you think its worth to move out of the repo or keep it inside the same repo ? Keeping it inside the same means there need a wrapper for Aura.Filter . Else it would have been easy.

Thank you.

**Comment by pmjones** [comment]
Hi @harikt -- I like the idea of a Filter_Interface package. :-)

**Comment by harikt** [comment]
@pmjones then its time for you to create the repo for it and so we can push some code.

We can also do something like you did for pds/skelton also  if needed ;-)

Thank you.

**Comment by pmjones** [comment]
Done! You're also now an owner on the repo. :-)

**Comment by harikt** [comment]
Thank you :-) . Do you have any thoughts / feedback on the interface itself ?

**Comment by pmjones** [comment]
AFAICT they match what we have already, so they look fine to me -- nicely done. (I reserve the right to change my mind. ;-)

**Comment by harikt** [comment]
I pushed the code : https://github.com/auraphp/Aura.Filter_Interface .

Will try to work on Aura.Input this weekend.

**Comment by harikt** [comment]
Some concerns are raised on https://github.com/auraphp/Aura.Input/issues/66 . Looks right to me.

**Comment by harikt** [comment]
I am closing this issue, for we have only one concern now which @jakejohns has raised in #66 .
