### ISSUE TITLE
Why no setOptions on Fieldset?

### ISSUE THREAD

**Issue by rk** [auraphp/Aura.Input#67]
Hello,

I'm dealing with a situation where I need to use `$fieldset->options` during validation. There's no way to inject it in through the factory, and no way to call `$fieldset->setOptions()`. For example:

``` php
class PriceRangeFieldset extends Fieldset {

    public function init() {
        $this->setField('low', 'number');
        $this->setField('high', 'number');

        $this->addRule('low', "The {$this->options['label']} low field only accepts digits.", function ($value) {
            return $value === null || $value === '' || ctype_digit($value);
        });

        $this->addRule('high', "The {$this->options['label']} high field only accepts digits.", function ($value) {
            return $value === null || $value === '' || ctype_digit($value);
        });
    }

}
```

And in the form:

``` php
class MyForm extends Form {

    public function init() {
        $this->setFieldset('design', 'price-range')
            ->setOptions(['label' => 'Design']);

        $this->setFieldset('development', 'price-range')
            ->setOptions(['label' => 'Development']);
    }

}
```

Was there a choice to prevent this use-case?

**Comment by harikt** [comment]
Your example looks good. One question I have is there is no `addRule` in `Fieldset` itself right ? So how are you using the same?

I don't have an answer for your question though.

## Optons

1. Move the validator to the form, but I do understand that means you need to write the same rule.
2. Add multiple field sets and pass options as 3rd parameter https://github.com/auraphp/Aura.Input/blob/e9805708280c64e72573ccc60c2cd9972a6459b8/tests/Aura/Input/Example/ExampleTest.php#L14-L19

**Comment by rk** [comment]
The code above isn't actually a copy/paste, but more of a test case I coded from the project I'm working on. You're right, the code fieldset should actually be:

``` php
class PriceRangeFieldset extends Fieldset {

    public function init() {
        $this->setField('low', 'number');
        $this->setField('high', 'number');

        $filters = $this->getFilter();

        $filters->addRule('low', "The {$this->options['label']} low field only accepts digits.", function ($value) {
            return $value === null || $value === '' || ctype_digit($value);
        });

        $filter->addRule('high', "The {$this->options['label']} high field only accepts digits.", function ($value) {
            return $value === null || $value === '' || ctype_digit($value);
        });
    }

}
```

The problem with adding a factory method to the Builder is simple: what if I want 4x of the same thing with different labels? The factory object does not pass parameters to the closure. For instance:

``` php
$form->setFieldset('my-name', 'price-range', "anything after the 2nd parameter is discarded...");
```

https://github.com/auraphp/Aura.Input/blob/e9805708280c64e72573ccc60c2cd9972a6459b8/src/Aura/Input/Builder.php#L96-L105

As you can see, nothing is passed into the closure. Therefore, it cannot derive anything from the context it was initialized in.

The example you showed works for small forms only. I have a form with 6 columns and 8 rows long as one "answer", so creating 8 fieldsets helps me a great deal. I'm considering forking the repo, making the changes I need, and then referencing it here (possibly as a pull request if you guys like it).

**Comment by harikt** [comment]
@rk sure feel free to fork and send PR.

If anyone accepts we can merge here. ( may be not for 1.x if it is breaking changes ) . In the mean time I will also think about this.
