### ISSUE TITLE
getField and getFields

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Input#7]
I feel there is an inconsistency in the output provided by both.

For eg :+1: 

``` php
    public function getField($name)
    {
        $value = isset($this->values[$name])
               ? $this->values[$name]
               : null;

        return ['name' => $name]
             + $this->fields->get($name)->asArray()
             + ['value' => $value];
    }

    public function getFields()
    {
        return $this->fields;
    }
```

The `getField` returns an array and `getFields` returns a `FieldCollection` .

Wondering whether it is good to have return `Field` itself than an array for `getField` .

https://github.com/auraphp/Aura.Input/blob/develop/src/Aura/Input/Form.php#L92

**Comment by pmjones** [comment]
Agreed. This is addressed in the "form" branch, where we have getInput() to get the actual input object, and get() to get the field as an array (or the actual input object in the case of fieldsets and fieldset collections).
