### ISSUE TITLE
What is the future of this project?

### ISSUE THREAD

**Issue by rotexdegba** [auraphp/Aura.Input#70]
What is the future of this project? In my opinion, it is feature complete and only needs to have the latest versions of PHP (7.3, 7.4 & 8.0 as of this writing) tested via travis or Github Actions to ensure it continues to work with the currently supported version of PHP. Will anyone be updating the CI tests for this project?

**Comment by harikt** [comment]
Hi @rotexdegba ,

This is an open-source project so any contributions are always welcome. When I get some time I will be updating the CI.

UPDATE : I have made a PR : https://github.com/auraphp/Aura.Input/pull/71 which we will merge in up coming days.
