### ISSUE TITLE
Good to have a solution, probably in Framework?

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Input#9]
Some times we will be having input of 

```
<input type="text" name="title[]" id="title0" value="some value" />
```

In this case the filter can be

``` php
$filter->addSoftRule('title', $filter::IS, 'alnum');
```

Which needs to be validated for all the title array. Rather than we writing `title0` it is always wise to have the `title[]` field.

We want to find a way that passing the value to filter can be addressed. Not sure whether it should come in `Aura.Filter` or `Aura.Input`

**Comment by pmjones** [comment]
Seems like the kind of thing we could do at the Filter level.  We have "any" and "all".  Perhaps we need a "repeated" or "multiple" filter that loops through the value array and applies rules to each element in the value array.

**Comment by harikt** [comment]
Will you be adding to the todo or making a issue there ?
